name: TEST
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  echo:
    name: echo github variables
    runs-on: ubuntu-latest
    steps:
      - name: echo github.ref_name
        run: echo ${{ github.ref_name }}
      - name: echo github.run_number
        run: echo ${{ github.run_number }}
      - name: echo github.ref_type
        run: echo ${{ github.ref_type }}
  publish:
    name: publish
    needs: echo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gnyahahha
          path: |
            coucou.txt
      # - name: publish release artifact
      #   if: github.ref_type == 'tag'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: coucou.txt
      #     tag_name: ${{ github.ref_name }}

