name: TEST
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  echo:
    name: echo github variables
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: blabla
        run: gh release view --json tagName -q .tagName
      - name: echo github.ref_name
        run: echo ${{ github.ref_name }}
      - name: echo github.run_number
        run: echo ${{ github.run_number }}
      - name: echo github.ref_type
        run: echo ${{ github.ref_type }}

      - name: Check branch for tag
        run: |
          git status
          git branch --show-current

  publish:
    name: publish
    needs: echo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gnyahahha
          path: |
            coucou.txt
      - name: Upload artifact on branch 'artifacts'
        if: github.ref_type == 'tag'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch origin artifacts
          git checkout artifacts
          git checkout ${{ github.ref_name }} "coucou.txt"
          git add *
          git status
          git diff --cached --quiet
          if [ $? -ne 0 ]; then
              git commit -m "Add artifacts from version $VERSION"
              git push
          fi
          git checkout ${{ github.ref_name }}
      # - name: publish release artifact
      #   if: github.ref_type == 'tag'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: coucou.txt
      #     tag_name: ${{ github.ref_name }}

